export default [
  { code: '501001', key: 'sysDictionary', url: '/commonbase/v1/sysDictionary', dis: '获取指定数据字典' },
  { code: '501001', key: 'getSysObject', url: '/sysObject/v1/getSysObject', dis: '获取系统对象' },
  { code: '501002', key: 'userBasicInfo', url: '/commonbase/v1/userBasicInfo', dis: '获取用户基本信息' },
  { code: '501012', key: 'userTodoWorkflowNum', url: '/commonbase/v1/userTodoWorkflowNum', dis: '获取待办流程数' },
  { code: '501027', key: 'userShortcutMenuConfig', url: '/commonbase/v1/userShortcutMenuConfig', dis: '查询用户快捷菜单配置' },
  { code: '501028', key: 'userProjectUpdate', url: '/commonbase/v1/userProjectUpdate', dis: '更新用户最近方案' },
  { code: '501026', key: 'userMenuProject', url: '/commonbase/v1/userMenuProject', dis: '获取用户菜单方案' },
  { code: '', key: 'dynamicReminder', url: '/statistics/homePage/v1/dynamicReminder', dis: '动态提醒' },
  { code: '', key: 'sysParam', url: '/commonbase/v1/sysParam', dis: '获取几个平台rul' },
  { code: '', key: 'queryInnerObject', url: '/commonbase/v1/queryInnerObject', dis: '获取内部对象' },
  { code: '', key: 'downloadFile', url: '/commonbase/v1/downloadFile', dis: 'livebos附件下载' },
  { code: '', key: 'queryProcessNavigation', url: '/basicservices/v1/queryProcessNavigation', dis: '流程导航查询' },
  { code: '', key: 'queryOtherUsers', url: '/commonbase/v1/queryOtherUsers', dis: '获取人员其他用户' },
  { code: '', key: 'downloadAttachmentOfDocumentByZip', url: '/api/attachment/v1/downloadAttachmentOfDocumentByZip', dis: '产品文档打包下载' },
  { code: '', key: 'uploadProto', url: '/commonbase/v1/uploadProto', dis: '人员头像图片上传入口' },
];
