export default [
  { code: '210046ES', key: 'addPool', url: '/customerbase/v1/addPool', dis: '客户通用  加入客户池功能(ES)' },
  { code: '220001', key: 'cusBasicInfo', url: '/customerbase/v1/cusBasicInfo', dis: '客户通用  获取客户基础信息' },
  { code: '220002', key: 'cusMoreInfo', url: '/customerbase/v1/cusMoreInfo', dis: '客户通用  获取客户详细信息' },
  { code: '220030', key: 'cusValueInfo', url: '/customerbase/v1/cusValueInfo', dis: '客户通用  客户基础-获取单客户价值数据' },
  { code: '220034', key: 'cusAppropriateInfo', url: '/customerbase/v1/cusAppropriateInfo', dis: '客户全景-适当性信息  获取客户适当性基础数据' },
  { code: '220200', key: 'updateCusBasicInfo', url: '/customerbase/v1/updateCusBasicInfo', dis: '客户通用  维护客户基础信息' },
  { code: '220009', key: 'saveSearchScheme', url: '/customerbase/v1/saveSearchScheme', dis: '客户通用  保存搜索方案(含搜索条件和设置的显示字段)' },
  { code: '230001', key: 'myCommonSearch', url: '/customerbase/v1/myCommonSearch', dis: '客户列表  获取客户列表-常用搜索' },
  { code: '230002', key: 'mySearchScheme', url: '/customerbase/v1/mySearchScheme', dis: '高级筛选  获取高级查询-搜索方案' },
  { code: '230003', key: 'searchSchemeDetail', url: '/customerbase/v1/searchSchemeDetail', dis: '客户通用  获取搜索方案内容明细' },
  { code: '230004', key: 'saveMySearchInfo', url: '/customerbase/v1/saveMySearchInfo', dis: '客户通用  保存用户查询信息' },
  { code: '210068', key: 'saveContactWay', url: '/customerbase/v1/saveContactWay', dis: '客户通用  维护客户其他联系方式' },
  { code: '220011', key: 'cusExistingLable', url: '/customerbase/v1/cusExistingLable', dis: '客户标签  获取客户已有标签' },
  { code: '220011', key: 'cusExistingAndSysLable', url: '/customerbase/v1/cusExistingAndSysLable', dis: '客户标签  获取客户已有标签和系统标签' },
  { code: '220012', key: 'myCusLable', url: '/customerbase/v1/myCusLable', dis: '客户标签  获取用户可操作客户标签' },
  { code: '220013', key: 'managingMyLable', url: '/customerbase/v1/managingMyLable', dis: '客户标签  自定义标签处理(新建、删除)' },
  { code: '220017', key: 'managingCusLable', url: '/customerbase/v1/managingCusLable', dis: '客户标签  操作客户标签' },
  { code: '220002', key: 'cusBelongsGroup', url: '/customerbase/v1/cusBelongsGroup', dis: '客户群  获取客户所属客户群' },
  { code: '220004', key: 'cusGroupCusList', url: '/customerbase/v1/cusGroupCusList', dis: '客户群  获取客户群客户' },
  { code: '220008', key: 'myCusGroup', url: '/customerbase/v1/myCusGroup', dis: '客户群  获取用户可选客户群' },
  { code: '502506', key: 'myCusGroupDetail', url: '/customerbase/v1/myCusGroupDetail', dis: '客户群  获取用户可选客户群' },
  { code: '220018', key: 'managingCusGroup', url: '/customerbase/v1/managingCusGroup', dis: '客户群  客户群操作(创建客户群、修改和删除群)' },
  { code: '220021', key: 'managingGroupCus', url: '/customerbase/v1/managingGroupCus', dis: '客户群  群客户操作(添加客户进群、从群中删除客户)' },
  { code: 'cusGroupImport', key: 'cusGroupImport', url: '/customerbase/v1/cusGroupImport', dis: '客户群  客户导入过程中使用返回值检查导入成功与否' },
  { code: 'importGroupCus', key: 'importGroupCus', url: '/customerbase/v1/importGroupCus', dis: '客户群  客户导入' },
  { code: 'importGroupCusInfo', key: 'importGroupCusInfo', url: '/customerbase/v1/importGroupCusInfo', dis: '客户群  查询待导入客户群客户信息导入成功渲染列表' },
  { code: '220003', key: 'cusLifeCycleView', url: '/customerbase/v1/cusLifeCycleView', dis: '客户全景-概览  客户全景获取客户生命周期视图' },
  { code: '200007', key: 'cusPreviousCoreData', url: '/customerbase/v1/cusPreviousCoreData', dis: '客户全景-概览  获取客户上日核心数据_合并账户' },
  { code: '200008', key: 'cusQuotaOverview', url: '/customerbase/v1/cusQuotaOverview', dis: '客户全景-概览  获取客户环比数据_合并账户' },
  { code: '200014', key: 'cusAssetsCoreData', url: '/customerbase/v1/cusAssetsCoreData', dis: '客户全景-持仓交易  获取客户资产核心数据' },
  { code: '200013', key: 'cusTradeOverview', url: '/customerbase/v1/cusTradeOverview', dis: '客户全景-持仓交易  获取合并账户概览数据' },
  { code: '200015', key: 'cusGeneralTradeOverview', url: '/customerbase/v1/cusGeneralTradeOverview', dis: '客户全景-持仓交易  获取普通账户概览数据' },
  { code: '200016', key: 'cusCreditTradeOverview', url: '/customerbase/v1/cusCreditTradeOverview', dis: '客户全景-持仓交易  获取信用账户概览数据' },
  { code: '200017', key: 'cusFinancialTradeOverview', url: '/customerbase/v1/cusFinancialTradeOverview', dis: '客户全景-持仓交易  获取理财账户概览数据' },
  { code: '200018', key: 'cusStockOptionTradeOverview', url: '/customerbase/v1/cusStockOptionTradeOverview', dis: '客户全景-持仓交易  获取股票期权账户概览数据' },
  { code: '20001X', key: 'cusTradePosition', url: '/customerbase/v1/cusTradePosition', dis: '客户全景-持仓交易  获取客户合并账户持仓' },
  { code: '200019', key: 'cusGeneralTradePosition', url: '/customerbase/v1/cusGeneralTradePosition', dis: '客户全景-持仓交易  获取客户普通账户持仓' },
  { code: '200020', key: 'cusCreditTradePosition', url: '/customerbase/v1/cusCreditTradePosition', dis: '客户全景-持仓交易  获取客户信用账户持仓' },
  { code: '200021', key: 'cusFinancialTradePosition', url: '/customerbase/v1/cusFinancialTradePosition', dis: '客户全景-持仓交易  获取客户理财账户持仓' },
  { code: '200022', key: 'cusStockOptionTradePosition', url: '/customerbase/v1/cusStockOptionTradePosition', dis: '客户全景-持仓交易  获取客户股票期权账户持仓' },
  { code: '210016', key: 'cusCreditDebtInfo', url: '/customerbase/v1/cusCreditDebtInfo', dis: '客户全景-持仓交易  获取客户信用负债信息' },
  { code: '210017', key: 'cusCreditContractInfo', url: '/customerbase/v1/cusCreditContractInfo', dis: '客户全景-持仓交易  获取客户信用合同信息' },
  { code: '210034', key: 'cusAccountCoreData', url: '/customerbase/v1/cusAccountCoreData', dis: '客户全景-账户信息  获取账户核心数据' },
  { code: '210035', key: 'cusShareholderAccount', url: '/customerbase/v1/cusShareholderAccount', dis: '客户全景-账户信息  获取客户股东账户数据' },
  { code: '210036', key: 'cusBankAccount', url: '/customerbase/v1/cusBankAccount', dis: '客户全景-账户信息  获取客户银行账户数据' },
  { code: '210037', key: 'cusCreditAccount', url: '/customerbase/v1/cusCreditAccount', dis: '客户全景-账户信息  获取客户信用账户数据' },
  { code: '210038', key: 'cusCreditAccountContract', url: '/customerbase/v1/cusCreditAccountContract', dis: '客户全景-账户信息  获取客户信用账户合同信息' },
  { code: '210039', key: 'cusFundAccount', url: '/customerbase/v1/cusFundAccount', dis: '客户全景-账户信息  获取客户基金账户信息' },
  { code: '210040', key: 'cusOTCAccount', url: '/customerbase/v1/cusOTCAccount', dis: '客户全景-账户信息  获取客户理财账户信息' },
  { code: '210041', key: 'cusStockOptionAccount', url: '/customerbase/v1/cusStockOptionAccount', dis: '客户全景-账户信息  获取客户股票期权账户信息' },
  { code: '210042', key: 'cusStockOptionAccountControl', url: '/customerbase/v1/cusStockOptionAccountControl', dis: '客户全景-账户信息  获取客户股票期权账户控制信息' },
  { code: '210043', key: 'prodHoldingCus', url: '/customerbase/v1/prodHoldingCus', dis: '金融产品全景  获取持仓客户列表' },
  { code: '210043', key: 'prodHoldingCus', url: '/customerbase/v1/prodHoldingCus', dis: '金融产品全景  获取持仓客户列表' },
  { code: '210044', key: 'cusKYCInfo', url: '/customerbase/v1/cusKYCInfo', dis: '客户全景-KYC  获取客户KYC数据' },
  { code: '210045', key: 'cusBusinessRightsInfo', url: '/customerbase/v1/cusBusinessRightsInfo', dis: '客户全景-业务权限开通  获取业务权限开通情况' },
  { code: '220010', key: 'cusListDisplayColumn', url: '/customerbase/v1/cusListDisplayColumn', dis: '查询客户列表可显示列  查询客户列表可显示列' },
  { code: '220011', key: 'cusListMetadata', url: '/customerbase/v1/cusListMetadata', dis: '查询客户列表元数据  查询客户列表元数据' },
  { code: '210049', key: 'cusServicePlan', url: '/basicservices/v1/cusServicePlan', dis: '客户通用  客户服务计划查询' },
  { code: '210048', key: 'cusKYCSplicingInfo', url: '/customerbase/v1/cusKYCSplicingInfo', dis: '客户全景  单客户背景信息查询' },
  { code: '502640', key: 'cusOtherConnections', url: '/customerbase/v1/cusOtherConnections', dis: '客户全景  客户其他联系方式' },
  { code: '502104', key: 'saveContactWay', url: '/customerbase/v1/saveContactWay', dis: '客户全景  修改客户联系方式' },
  { code: '', key: 'orderServer', url: '/customerbase/v1/orderServer', dis: '客户列表  定服务' },
  { code: '', key: 'cusAnalysisQuota', url: '/customerbase/v1/cusAnalysisQuota', dis: '客户通用  获取客户分析指标' },
  { code: '502404', key: 'addCusTags', url: '/customerbase/v1/addCusTags', dis: '客户列表  打标签' },
  { code: 'exportData', key: 'exportData', url: '/customerbase/v1/exportData', dis: '导出  客户列表-导出操作' },
  { code: '502450', key: 'cusLabelClassification', url: '/customerbase/v1/cusLabelClassification', dis: '客户分析  标签分类' },
  { code: '510201', key: 'customerProfile', url: '/customerbase/v1/customerProfile', dis: '客户首页  相关概要数据' },
  { code: '502205', key: 'cusHotSearchQuota', url: '/customerbase/v1/cusHotSearchQuota', dis: '客户  热门搜索条件' },
  { code: '501011', key: 'userUnreadNoticeMsgNum', url: '/commonbase/v1/userUnreadNoticeMsgNum', dis: '获取未读知会消息数' },
  { code: '501012', key: 'userTodoWorkflowNum', url: '/commonbase/v1/userTodoWorkflowNum', dis: '获取待办流程数' },
  { code: '502100', key: 'cusRangeType', url: '/customerbase/v1/cusRangeType', dis: '根据系统角色获取客户范围类型' },
  { code: '510108', key: 'staffCusDynamics', url: '/customerbase/v1/staffCusDynamics', dis: '系统首页  人员名下客户动态' },
  { code: '510109', key: 'staffCusDynamicDetails', url: '/customerbase/v1/staffCusDynamicDetails', dis: '系统首页  人员名下客户动态详情明细' },
  { code: '502207', key: 'nonTradableShareCus', url: '/customerbase/v1/nonTradableShareCus', dis: '客户首页  实时提醒-大小非客户' },
  { code: '502208', key: 'potLossCus', url: '/customerbase/v1/potLossCus', dis: '客户首页-实时提醒-潜在流失客户' },
  { code: '510301', key: 'iPOReminds', url: '/customerbase/v1/iPOReminds', dis: '客户首页-实时提醒-新股中签' },
  { code: '510302', key: 'prodMaturityReminds', url: '/customerbase/v1/prodMaturityReminds', dis: '客户首页-实时提醒-产品到期' },
  { code: '510303', key: 'largeFundsTransferReminds', url: '/customerbase/v1/largeFundsTransferReminds', dis: '客户首页-实时提醒-大额资金转入转出' },
  { code: '502212', key: 'keyCus', url: '/customerbase/v1/keyCus', dis: '客户首页-实时提醒-重点客户' },
  { code: '502116', key: 'aggregateDimensionIndicator', url: '/customerbase/v1/aggregateDimensionIndicator', dis: '客户聚合--获取客户聚合统计维度输出指标' },
  { code: '502117', key: 'transFlowStats', url: '/customerAggs/v2/transFlowStats', dis: '客户聚合--我的客户、团队客户交易流水统计' },
  { code: '502118', key: 'transFlowStatsForBO', url: '/customerAggs/v2/transFlowStatsForBO', dis: '客户聚合--营业部交易流水统计' },
  { code: '502115', key: 'myAggregateScheme', url: '/customerbase/v1/myAggregateScheme', dis: '客户聚合--获取我的客户聚合方案' },
  { code: '502114', key: 'saveAggregateScheme', url: '/customerbase/v1/saveAggregateScheme', dis: '客户聚合--保存我的客户聚合方案 1|新增;2|修改;3|删除' },
  { code: '502119', key: 'holdPositionStatsForBO', url: '/customerAggs/v2/holdPositionStatsForBO', dis: '客户聚合--营业部持仓统计' },
  { code: '502120', key: 'holdPositionStats', url: '/customerAggs/v2/holdPositionStats', dis: '客户聚合--客户团队持仓统计' },
  { code: 'cusAggs', key: 'cusAggs', url: '/customerAggs/v2/cusAggs', dis: '客户聚合--基础指标统计' },
  { code: '', key: 'holdPosition', url: '/customerAggs/v2/holdPosition', dis: '客户聚合--持仓-我的客户、团队客户持仓查询' },
  { code: '', key: 'holdPositionForBO', url: '/customerAggs/v2/holdPositionForBO', dis: '客户聚合--持仓-营业部持仓查询' },
  { code: '', key: 'transFlow', url: '/customerAggs/v2/transFlow', dis: '客户聚合--我的客户、团队客户交易流水查询' },
  { code: '', key: 'transFlowForBO', url: '/customerAggs/v2/transFlowForBO', dis: '客户聚合--营业部交易流水查询' },
  { code: '', key: 'cashFlowModel', url: '/customerAggs/v2/cashFlow', dis: '客户聚合--资金流水查询' },
  { code: '', key: 'cashFlowForBO', url: '/customerAggs/v2/cashFlowForBO', dis: '客户聚合--资金流水查询-营业部' },
  // 客户画像
  { code: '502632', key: 'cusSysemLable', url: '/customerbase/v1/cusSystemLable', dis: '获取客户系统标签' },
  { code: '502633', key: 'cusSysemLableHis', url: '/customerbase/v1/cusSystemLableHis', dis: '服获取客户系统标签历史' },
  { code: '502634', key: 'cusKYCSplicingInfoConfigCate', url: '/customerbase/v1/cusKYCSplicingInfoConfigCate', dis: '获取KYC背景信息配置分类' },
  { code: '502635', key: 'cusKYCSplicingInfoConfig', url: '/customerbase/v1/cusKYCSplicingInfoConfig', dis: '获取KYC背景信息配置' },
  { code: '502636', key: 'cusReturnVisitInfo', url: '/customerbase/v1/cusReturnVisitInfo', dis: '服务信息 客户回访信息' },
  { code: '502637', key: 'cusComplaintInfo', url: '/customerbase/v1/cusComplaintInfo', dis: '服务信息 客户投诉信息' },
  { code: '502641', key: 'customerPortraitLabel', url: '/customerbase/v1/customerPortraitLabel', dis: '客户全景 画像  系统标签' },
  { code: '502643', key: 'cusSuitProducts', url: '/customerbase/v1/cusSuitProducts', dis: '客户全景  查询客户适合产品列表' },
  { code: '502644', key: 'cusAssetsTrends', url: '/customerbase/v1/cusAssetsTrends', dis: '客户全景  查询客户资产趋势' },
  { code: '502643', key: 'cusOpenBusiness', url: '/customerbase/v1/cusOpenBusiness', dis: '客户全景  查询客户开通业务，可开通业务' },
  { code: '502645', key: 'assetDistribution', url: '/customerbase/v1/assetDistribution', dis: '客户全景  投资分析-资产分布' },
  { code: '502645', key: 'assetInfo', url: '/customerbase/v1/assetInfo', dis: '客户全景  投资分析-资产信息' },
  { code: '502646', key: 'statementBaseInfo', url: '/customerbase/v1/statementBaseInfo', dis: '客户全景  投资分析-账单信息' },
  { code: '502647', key: 'statementDetailInfo', url: '/customerbase/v1/statementDetailInfo', dis: '客户全景  投资分析-账单详细信息' },
  { code: '502648', key: 'investmentAbility', url: '/customerbase/v1/investmentAbility', dis: '客户全景  投资分析-投资能力' },
  { code: '502649', key: 'investmentKeyWord', url: '/customerbase/v1/investmentKeyWord', dis: '客户全景  投资分析-投资关键字' },
  { code: '5026410', key: 'profitCalendar', url: '/customerbase/v1/profitCalendar', dis: '客户全景  投资分析-盈亏日历' },
  { code: '5026411', key: 'investmentPreferences', url: '/customerbase/v1/investmentPreferences', dis: '客户全景  投资分析-投资偏好' },
  { code: '5026412', key: 'growthRateTrend', url: '/customerbase/v1/growthRateTrend', dis: '客户全景  投资分析-总资产增长率' },
  { code: '5026413', key: 'totalAssetChange', url: '/customerbase/v1/totalAssetChange', dis: '客户全景  投资分析-总资产变动' },
  { code: '5026414', key: 'investmentStyle', url: '/customerbase/v1/investmentStyle', dis: '客户全景  投资分析-投资风格' },
  { code: '5026415', key: 'profitStocking', url: '/customerbase/v1/profitStocking', dis: '客户全景  投资分析-盈利股票' },
  // 从dsc迁过来的
  { code: '510507', key: 'cusDealDetails', url: '/customerbase/v1/cusDealNewDetails', dis: '客户全景  获取客户合并账户时间段内成交流水' },
  { code: '510516', key: 'cusGeneralDealDetails', url: '/customerbase/v1/cusGeneralDealNewDetails', dis: '客户全景  获取客户普通账户时间段内成交流水' },
  { code: '510525', key: 'cusCreditDealDetails', url: '/customerbase/v1/cusCreditDealNewDetails', dis: '客户全景  获取客户信用账户时间段内成交流水' },
  { code: '510534', key: 'cusFinancialDealDetails', url: '/customerbase/v1/cusFinancialDealNewDetails', dis: '客户全景  获取客户理财账户时间段内成交流水' },
  { code: '510535', key: 'cusFinancialEntrustNewDetails', url: '/customerbase/v1/cusFinancialEntrustNewDetails', dis: '客户全景  获取客户理财账户时间段内委托流水' },
  { code: '510536', key: 'cusStockOptionDealDetails', url: '/customerbase/v1/cusStockOptionDealNewDetails', dis: '客户全景  获取客户股票期权账户时间段内成交流水' },
  { code: '510508', key: 'cusEntrustDetails', url: '/customerbase/v1/cusEntrustNewDetails', dis: '客户全景  获取客户合并账户时间段内委托流水' },
  { code: '510517', key: 'cusGeneralEntrustDetails', url: '/customerbase/v1/cusGeneralEntrustNewDetails', dis: '客户全景  获取客户普通账户时间段内委托流水' },
  { code: '510526', key: 'cusCreditEntrustDetails', url: '/customerbase/v1/cusCreditEntrustNewDetails', dis: '客户全景  获取客户信用账户时间段内委托流水' },
  { code: '510537', key: 'cusStockOptionEntrustDetails', url: '/customerbase/v1/cusStockOptionEntrustNewDetails', dis: '客户全景  获取客户股票期权账户时间段内委托流水' },
  { code: '510509', key: 'cusCapitalDetails', url: '/customerbase/v1/cusCapitalNewDetails', dis: '客户全景  获取客户合并账户时间段内资金流水' },
  { code: '510518', key: 'cusGeneralCapitalDetails', url: '/customerbase/v1/cusGeneralCapitalNewDetails', dis: '客户全景  获取客户普通账户时间段内资金流水' },
  { code: '510527', key: 'cusCreditCapitalDetails', url: '/customerbase/v1/cusCreditCapitalNewDetails', dis: '客户全景  获取客户信用账户时间段内资金流水' },
  { code: '510538', key: 'cusStockOptionCapitalDetails', url: '/customerbase/v1/cusStockOptionCapitalNewDetails', dis: '客户全景  获取客户股票期权账户时间段内资金流水' },
  { code: '510540', key: 'cusGetVocation', url: '/customerbase/v1/cusGetVocation', dis: '客户全景  单客户开通业务情况' },
  { code: '502638', key: 'cusStarChangeHis', url: '/customerbase/v1/cusStarChangeHis', dis: '客户全景  获取客户星级变动信息' },
  { code: '510541', key: 'cusRelationshipChangeLog', url: '/customerbase/v1/cusRelationshipChangeLog', dis: '客户全景 查询客户关系变动日志' },
  { code: '502650', key: 'offsiteCancelAccountStatistics', url: '/customerbase/v1/offsiteCancelAccountStatistics', dis: '查询非现场销户统计' },
  { code: '502651', key: 'offsiteCancelAccountInfo', url: '/customerbase/v1/offsiteCancelAccountInfo', dis: '查询非现场销户数据' },
  { code: '502652', key: 'offsiteCancelAccountTrend', url: '/customerbase/v1/offsiteCancelAccountTrend', dis: '查询非现场销户趋势' },
  // 用户场景化
  { code: '502701', key: 'userScenarioLabelConfigList', url: '/customerbase/v1/userScenarioLabelConfigList', dis: '查询用户场景化标签配置' },
  { code: '502702', key: 'userScenarioLabelConfig', url: '/customerbase/v1/userScenarioLabelConfig', dis: '用户场景化标签配置' },
  // -------------- customer label ---------------
  { code: '502801', key: 'cusLabelConfigList', url: '/customerbase/v1/cusLabelConfigList', dis: '获取客户标签配置列表' },
  { code: '502802', key: 'cusLabelConfigDetail', url: '/customerbase/v1/cusLabelConfigDetail', dis: '获取客户标签配置明细' },
  { code: '502803', key: 'cusLabelRuleDefine', url: '/customerbase/v1/cusLabelRuleDefine', dis: '获取客户标签规则定义明细' },
  { code: '502804', key: 'cusLabelValueDefine', url: '/customerbase/v1/cusLabelValueDefine', dis: '获取客户标签配置-标签值定义' },
  { code: '502805', key: 'cusLabelValueConfig', url: '/customerbase/v1/cusLabelValueConfig', dis: '客户标签配置-标签值操作' },
  { code: '502806', key: 'cusLabelConfigLabelList', url: '/customerbase/v1/cusLabelConfigLabelList', dis: '客户标签配置-获取可配置标签或指标列表' },
  { code: '502807', key: 'cusLabelParameter', url: '/customerbase/v1/cusLabelParameter', dis: '客户标签配置-标签值参数操作' },
  { code: '502808', key: 'cusLabelIndexExplain', url: '/customerbase/v1/cusLabelIndexExplain', dis: '客户标签配置-指标解释' },
  { code: '502809', key: 'updateLabelValueSeq', url: '/customerbase/v1/updateLabelValueSeq', dis: '客户标签配置-更新标签排序' },
  // -------------- /customer label ---------------
  // 东莞项目新增
  { code: '', key: 'userGroupOper', url: '/customerbase/v1/userGroupOper', dis: '用户群编辑' },
  { code: '502605', key: 'labelCircleQueryGroup', url: '/customerbase/v1/labelCircleQueryGroup', dis: '查询用户可选用户群' },
  { code: '', key: 'userGroupLstExport', url: '/customerbase/v1/userGroupLstExport', dis: '用户群数据导出' },
  { code: '', key: 'labelCircleSaveScheme', url: '/customerbase/v1/labelCircleSaveScheme', dis: '标签圈人保存方案' },
  { code: '', key: 'labelCircleQueryScheme', url: '/customerbase/v1/labelCircleQueryScheme', dis: '标签圈人查询方案' },
  // -------------- /customer label ---------------
  { code: 'exportCusGroupData', key: 'exportCusGroupData', url: '/cusgroupbase/v1/exportCusGroupData', dis: '导出客群数据' },
  { code: '502708', key: 'cusApprQuestionnaire', url: '/customerbase/v1/cusApprQuestionnaire', dis: '适当性-问卷' },
  { code: '502707', key: 'cusProductPosition', url: '/customerbase/v1/cusProductPosition', dis: '适当性-客户产品持仓' },
  { code: '502705', key: 'cusConversionRecord', url: '/customerbase/v1/cusConversionRecord', dis: '适当性-客户转换记录' },
  { code: '502704', key: 'cusEvalustionDetail', url: '/customerbase/v1/cusEvalustionDetail', dis: '适当性-客户评测明细' },
  { code: '502706', key: 'cusEvalustionRecordList', url: '/customerbase/v1/cusEvalustionRecordList', dis: '适当性-查询客户风险评测流水' },
  { code: '502648', key: 'cusRelationList', url: '/customerbase/v1/cusRelationList', dis: '适当性-查询客户关系列表' },
  { code: '502643', key: 'cusOpenBusiness', url: '/customerbase/v1/cusOpenBusiness', dis: '适当性-查询客户开通业务、可开通业务' },
  { code: '502701', key: 'cusProfileInfo', url: '/customerbase/v1/cusProfileInfo', dis: '适当性-查询客户适当性概况信息' },
  { code: '502117', key: 'cusExtendInfo', url: '/customerbase/v1/cusExtendInfo', dis: '适当性-获取客户扩展信息' },
  { code: '502702', key: 'cusEvalustionAnalysis', url: '/customerbase/v1/cusEvalustionAnalysis', dis: '适当性-客户结果分析' },
  { code: '502703', key: 'cusEvalustionTrend', url: '/customerbase/v1/cusEvalustionTrend', dis: '适当性-客户评测结果趋势' },
  // 华创Kyc新增接口同步
  { code: '', key: 'cusKYCSplicingIndexRelateInfo', url: '/customerbase/v1/cusKYCSplicingIndexRelateInfo', dis: '获取客户KYC指标关联关系' },
  // 贵金属账户
  { code: '', key: 'cusPreciousMetalsAccount', url: '/customerbase/v1/cusPreciousMetalsAccount', dis: '获取客户贵金属账户信息' },
  { code: '', key: 'cusTradeOverview', url: '/customerbase/v1/cusTradeOverview', dis: '获取贵金属账户概览数据' },
  { code: '', key: 'cusAssetsTrends', url: '/customerbase/v1/cusAssetsTrends', dis: '查询客户资产趋势' },
  { code: '', key: 'cusPreciousMetalsPosition', url: '/customerbase/v1/cusPreciousMetalsPosition', dis: '获取客户贵金属账户持仓' },
  { code: '', key: 'cusPreciousMetalsStock', url: '/customerbase/v1/cusPreciousMetalsStock', dis: '获取客户贵金属账户持仓-库存信息' },
  { code: '', key: 'cusPreciousMetalsDealDetails', url: '/customerbase/v1/cusPreciousMetalsDealDetails', dis: '获取客户贵金属账户时间段内成交流水' },
  { code: '', key: 'cusPreciousMetalsEntrustDetails', url: '/customerbase/v1/cusPreciousMetalsEntrustDetails', dis: '获取客户贵金属账户时间段内委托流水' },
  { code: '', key: 'cusPreciousMetalsCapitalDetails', url: '/customerbase/v1/cusPreciousMetalsCapitalDetails', dis: '获取客户贵金属账户时间段内资金流水' },
  { code: '', key: 'cusAssetsSummary', url: '/customerbase/v1/cusAssetsSummary', dis: '获取账户月度查询' },
  { code: '', key: 'cusLifeCycleConditionConfig', url: '/customerbase/v1/cusLifeCycleConditionConfig', dis: '客群管理生命周期' },
  { code: '510110', key: 'staffCusDynamicDetails', url: '/customerbase/v1/staffCusDynamicDetails', dis: '首页-客户动态-动态详情' },
  // 财富管理 -----------------------------------
  { code: '520106', key: 'fortuneCusListCommonSearchInfo', url: '/customerbase/v1/fortuneCusListCommonSearchInfo', dis: '获取财富客户列表-常用搜索' },
  { code: '', key: 'cusAccountProfileData', url: '/customerbase/v1/cusAccountProfileData', dis: '财富管理-客户全景-账户概况' },
  { code: '', key: 'cusPortfolioYieldTrends', url: '/customerbase/v1/cusPortfolioYieldTrends', dis: '财富管理-客户全景-收益率曲线' },
  { code: '520103', key: 'focusCustomer', url: '/customerbase/v1/focusCustomer', dis: '财富管理-关注/取消关注客户' },
  { code: '', key: 'cusPositionRatioTrends', url: '/customerbase/v1/cusPositionRatioTrends', dis: '财富-账户诊断-客户仓位比例趋势' },
  { code: '', key: 'cusInvestmentPreferTopFive', url: '/customerbase/v1/cusInvestmentPreferTopFive', dis: '财富-账户诊断-客户投资板块偏好TOP5' },
  { code: '', key: 'cusStockPriceAndValueDistribution', url: '/customerbase/v1/cusStockPriceAndValueDistribution', dis: '财富-账户诊断-客户股价/估值分布' },
  { code: '', key: 'cusBenifitTrends', url: '/customerbase/v1/cusBenifitTrends', dis: '财富-账户诊断-客户收益走势对比图' },
  { code: '', key: 'cusFinancialProductsProportion', url: '/customerbase/v1/cusFinancialProductsProportion', dis: '财富-账户诊断-理财品种覆盖度' },
  { code: '', key: 'cusFinancialIntention', url: '/customerbase/v1/cusFinancialIntention', dis: '财富-账户诊断-客户理财意愿' },
  // /财富管理-----------------------------------
  // 客户持仓查询修改
  { code: '', key: 'cusPositionQuery', url: '/customerbase/v1/cusPositionQuery', dis: '客户持仓查询' },
  { code: '', key: 'entDetailsDeclarationResults', url: '/customerbase/v1/entDetailsDeclarationResults', dis: '持仓交易-委托明细-申报结果种类查询' },
  // 高净值客户-客户服务
  { code: '', key: 'firstServiceCustomerList', url: '/customerbase/v1/firstServiceCustomerList', dis: '高净值客户-客户服务左侧客户列表' },
  { code: '', key: 'requireClassingSearch', url: '/customerbase/v1/requireClassingSearch', dis: '高净值客户-客户服务-未服务-登记需求表单-需求类型' },
  { code: '', key: 'highNavRequireRegister', url: '/customerbase/v1/proHighNavRequireRegister', dis: '高净值客户-客户服务-未服务-登记需求' },
  { code: '', key: 'highNavBusinessOpportunity', url: '/customerbase/v1/highNavBusinessOpportunity', dis: '高净值客户-客户服务-未服务-客户机会标签' },
  { code: '', key: 'cusOrVisitorSuitProducts', url: '/customerbase/v1/cusOrVisitorSuitProducts', dis: '高净值客户-客户服务-未服务-游客推荐产品' },
	
  // 商机全景
  { code: '', key: 'businessProfile', url: '/customerbase/v1/businessProfile', dis: '高净值客户-商机全景-概况' },
  { code: '', key: 'businessFlowSearch', url: '/customerbase/v1/businessFlowSearch', dis: '高净值客户-商机全景-流水查询' },
  { code: '', key: 'businessOrderSearch', url: '/customerbase/v1/businessOrderSearch', dis: '高净值客户-商机全景-订单查询' },
  { code: '', key: 'businessProfileReq', url: '/customerbase/v1/businessProfileReq', dis: '高净值客户-商机全景-需求' },
  { code: '', key: 'proConfigurationPlanSearch', url: '/customerbase/v1/proConfigurationPlanSearch', dis: '高净值客户-方案配置操作-新增修改删除' },
  { code: '', key: 'searchConfigurationPlan', url: '/customerbase/v1/searchConfigurationPlan', dis: '高净值客户-配置方案查询' },
  { code: '', key: 'highNavCusProfile', url: '/customerbase/v1/highNavCusProfile', dis: '高净值客户首页-概要数据' },
  { code: '', key: 'highNavCusProfileRatio', url: '/customerbase/v1/highNavCusProfileRatio', dis: '高净值客户首页-概要数据比例' },
  { code: '', key: 'firstTimeServiceProfile', url: '/customerbase/v1/firstTimeServiceProfile', dis: '高净值客户首页-首次服务概况' },
  { code: '', key: 'highNavCusDemandDistribute', url: '/customerbase/v1/highNavCusDemandDistribute', dis: '高净值客户首页-客户需求分布' },
  { code: '', key: 'businessChanceMy', url: '/customerbase/v1/businessChanceMy', dis: '高净值客户首页-我的商机' },
  { code: '', key: 'businessChanceStands', url: '/customerbase/v1/businessChanceStands', dis: '高净值客户首页-商机看台' },
  { code: '', key: 'highNavMonthlyRevenueTrend', url: '/customerbase/v1/highNavMonthlyRevenueTrend', dis: '高净值客户首页-月度收入变动趋势' },
  { code: '', key: 'firstTimeServiceCustomer', url: '/customerbase/v1/firstTimeServiceCustomer', dis: '高净值客户首页-首次服务客户' },
  { code: '', key: 'highNavCusDemand', url: '/customerbase/v1/highNavCusDemand', dis: '高净值客户首页-首次服务客户' },
  { code: '', key: 'highNavChangeServerType', url: '/customerbase/v1/highNavChangeServerType', dis: '高净值客户首页-服务状态变更' },
  { code: '', key: 'highNavCusAllocateInquiry', url: '/customerbase/v1/highNavCusAllocateInquiry', dis: '高净值客户-客户分配查询' },
];
