export default [
  { code: '', key: 'querySocialRelationsInformation', url: '/panoramic/v1/querySocialRelationsInformation', dis: '获取待办数据详细列表' },
  { code: '', key: 'queryRecommendCustomerFund', url: '/card/v1/queryRecommendCustomerFund', dis: '客户推荐精选池基金' },
  { code: '', key: 'queryBusinessOpportunityList', url: '/panoramic/v1/queryBusinessOpportunityList', dis: '客户全景业务机会' },
  { code: '', key: 'queryLifeCycleList', url: '/panoramic/v1/queryLifeCycleList', dis: '客户生命周期' },
  { code: '', key: 'queryNormalAccountInformation', url: '/panoramic/v1/queryNormalAccountInformation', dis: '查询普通账户基本信息' },
  { code: '', key: 'queryCapitalAccountInformation', url: '/panoramic/v1/queryCapitalAccountInformation', dis: '查询资金账户列表' },
  { code: '', key: 'queryMasterBankInformation', url: '/panoramic/v1/queryMasterBankInformation', dis: '查询主，辅存管银行' },
  { code: '', key: 'queryNormalAndContractInformation', url: '/panoramic/v1/queryNormalAndContractInformation', dis: '查询合同和基本信息' },
  { code: '', key: 'queryGuAccountInformation', url: '/panoramic/v1/queryGuAccountInformation', dis: '查询信用股东账号' },
  { code: '', key: 'queryFinaceTaInformation', url: '/panoramic/v1/queryFinaceTaInformation', dis: '点击理财账户-开通的基金公司TA账户' },
  { code: '', key: 'queryDeptAccountInformation', url: '/panoramic/v1/queryDeptAccountInformation', dis: '点击理财账户-开通的银行理财账户' },
  { code: '', key: 'queryElectronicInformation', url: '/panoramic/v1/queryElectronicInformation', dis: '点击理财账户-资管产品电子合同签署情况' },
  { code: '', key: 'queryOpenConformation', url: '/panoramic/v1/queryOpenConformation', dis: '点击期权账户-查询基本信息' },
  { code: '', key: 'querySingleInformation', url: '/panoramic/v1/querySingleInformation', dis: '点击期权账户-开通合约列表' },
  { code: '', key: 'querySignProformation', url: '/panoramic/v1/querySignProformation', dis: '点击基金投顾-签约产品列表' },
  { code: '', key: 'queryCustAllInfo', url: '/panoramic/v1/queryCustAllInfoV3', dis: '获取客户基本信息1' },
  { code: '', key: 'queryCustAllInfoMore', url: '/panoramic/v1/queryCustAllInfoMore', dis: '获取客户基本信息2' },
  { code: '', key: 'updatePhoneInfo', url: '/panoramic/v1/updatePhoneInfo', dis: '客户联系方式更新' },
  { code: '', key: 'updateCharacteristicInfo', url: '/panoramic/v1/updateCharacteristicInfo', dis: '修改客户个性化信息' },
  { code: '', key: 'updaterelationshipInfo', url: '/panoramic/v1/updaterelationshipInfo', dis: '增加或则修改客户关系' },
  { code: '', key: 'queryAccountInformation', url: '/panoramic/v1/queryAccountInformation', dis: '账户概况' },
  { code: '', key: 'queryCustPointsDetails', url: '/panoramic/v1/queryCustPointsDetails', dis: '客户积分明细查询' },
  { code: '', key: 'queryServiceDynamicsList', url: '/panoramic/v1/queryServiceDynamicsList', dis: '服务动态' },
  { code: '', key: 'queryCustomerLabelList', url: '/panoramic/v1/queryCustomerLabelList', dis: '查询客户标签列表信息' },
  { code: '', key: 'saveAddCustomLabel', url: '/panoramic/v1/saveAddCustomLabel', dis: '新建自定义标签' },
  { code: '', key: 'saveAddCustomerLabel', url: '/panoramic/v1/saveAddCustomerLabel', dis: '新建客户打标签' },
  { code: '', key: 'queryDockingCommissionRateInfo', url: '/allMentionCommission/interestOptional/v1/queryDockingCommissionRateInfo', dis: '费率查询' },
  { code: '', key: 'queryHistoricalRateInformation', url: '/panoramic/v1/queryHistoricalRateInformation', dis: '获取历史费率信息查询' },
  { code: '', key: 'queryCommissionRateList', url: '/panoramic/v1/queryCommissionRateList', dis: '查询佣金费率信息列表' },

  { code: '', key: 'queryAssetPieChartInformation', url: '/panoramic/v1/queryAssetPieChartInformation', dis: '资产与贡献饼图信息查询' },
  { code: '', key: 'queryProgramIndicatorInformation', url: '/panoramic/v1/queryProgramIndicatorInformation', dis: '方案指标明细信息查询' },
  { code: '', key: 'saveProgramIndicatorInformation', url: '/panoramic/v1/saveProgramIndicatorInformation', dis: '方案指标明细信息保存' },
  { code: '', key: 'queryIndicatorSchemeDefinition', url: '/panoramic/v1/queryIndicatorSchemeDefinition', dis: '方案指标定义查询' },
  { code: '', key: 'queryAssetPlanTrendList', url: '/panoramic/v1/queryAssetPlanTrendList', dis: '资产方案趋势图' },
  { code: '', key: 'queryAssetPlanMonthList', url: '/panoramic/v1/queryAssetPlanMonthList', dis: '资产方案列表' },
  { code: '', key: 'queryCustomerContributionTrendList', url: '/panoramic/v1/queryCustomerContributionTrendList', dis: '贡献方案趋势图' },
  { code: '', key: 'queryCustomerContributionList', url: '/panoramic/v1/queryCustomerContributionList', dis: '贡献方案列表' },
  { code: '', key: 'queryAccountAnalysisListInfo', url: '/panoramic/v1/queryAccountAnalysisListInfo', dis: '账户分析列表' },
  { code: '', key: 'queryAccountAnalysisSum', url: '/panoramic/v1/queryAccountAnalysisSum', dis: '账户分析列表汇总' },
  { code: '', key: 'queryAssetPlanMonthListExport', url: '/panoramic/v1/queryAssetPlanMonthListExport', dis: '资产方案导出' },
  { code: '', key: 'queryCustomerContributionListExport', url: '/panoramic/v1/queryCustomerContributionListExport', dis: '贡献方案导出' },
  { code: '', key: 'queryAccountAnalysisListInfoExport', url: '/panoramic/v1/queryAccountAnalysisListInfoExport', dis: '账户分析导出' },
  { code: '', key: 'queryAccountAnalysisSumExport', url: '/panoramic/v1/queryAccountAnalysisSumExport', dis: '自定义方案汇总导出' },

  { code: '', key: 'queryProfitAllAcount', url: '/panoramic/v1/queryProfitAllAcount', dis: '交易全部账户列表' },
  { code: '', key: 'queryProfitAllAcountTable', url: '/panoramic/v1/queryProfitAllAcountTable', dis: '查询成交流水全部账户图标' },
  { code: '', key: 'queryProfitNormalAcount', url: '/panoramic/v1/queryProfitNormalAcount', dis: '查询成交流水全部账户图标' },
  { code: '', key: 'queryProfitfinanAcount', url: '/panoramic/v1/queryProfitfinanAcount', dis: '查询成交理财账户列表' },
  { code: '', key: 'queryProfitOptionAcount', url: '/panoramic/v1/queryProfitOptionAcount', dis: '查询成交流水期权账户列表' },
  { code: '', key: 'queryCapitalFlowAccount', url: '/panoramic/v1/queryCapitalFlowAccount', dis: '查询资金流水' },

  { code: '', key: 'getProfitNormalListExport', url: '/panoramic/v1/getProfitNormalListExport', dis: '成交流水信用、普通导出' },
  { code: '', key: 'getProfitOptionListListExport', url: '/panoramic/v1/getProfitOptionListExport', dis: '成交流水期权账户导出' },
  { code: '', key: 'getProfitfinanListExport', url: '/panoramic/v1/getProfitfinanListExport', dis: '成交流水理财账户导出' },
  { code: '', key: 'getSucessWatertListExport', url: '/panoramic/v1/getSucessWatertListExport', dis: '成交流水全部账户导出' },
  { code: '', key: 'getCapitalListExport', url: '/panoramic/v1/getCapitalListExport', dis: '资金流水导出' },
  { code: '', key: 'getAppointmentExport', url: '/panoramic/v1/getAppointmentExport', dis: '预约流水导出' },

  { code: '', key: 'getProfitDate', url: '/panoramic/v1/getProfitDate', dis: '获取上一个交易日时间' },
  { code: '', key: 'queryFundInvestmentAccount', url: '/panoramic/v1/queryFundInvestmentAccount', dis: '查询成交流水基金投顾列表' },
  { code: '', key: 'queryFundInvestmentAccountExport', url: '/panoramic/v1/queryFundInvestmentAccountExport', dis: '成交流水基金投顾列表导出' },

  // 客户360优化
  { code: '', key: 'queryCustAllInfoBase', url: '/panoramic/v1/queryCustAllInfoBase', dis: '客户概况基本信息接口' },
];
