export default [
  { code: '', key: 'prodHomepageCalendar', url: '/prodHome/v1/prodHomepageCalendar', dis: '产品首页日历查询' },
  { code: '', key: 'calendarDetails', url: '/prodHome/v1/calendarDetails', dis: '日历明细查询' },
  { code: '', key: 'prodSummary', url: '/prodHome/v1/prodSummary', dis: '产品概况查询' },
  { code: '', key: 'prodSummaryDetail', url: '/prodHome/v1/prodSummaryDetail', dis: '产品概况明细查询' },
  { code: '', key: 'prodNotice', url: '/prodHome/v1/prodNotice', dis: '产品公告查询' },
  { code: '', key: 'prodMyApp', url: '/prodHome/v1/prodMyApp', dis: '我的应用查询' },
  { code: '', key: 'maintainMyApp', url: '/prodHome/v1/maintainMyApp', dis: '我的应用维护' },
  { code: '', key: 'msgProfile', url: '/prodHome/v1/msgProfile', dis: '消息概况查询' },
  { code: '', key: 'msgCenterQry', url: '/prodHome/v1/msgCenterQry', dis: '消息中心查询' },
  { code: '', key: 'msgUpdate', url: '/prodHome/v1/msgUpdate', dis: '消息更新维护' },
  { code: '', key: 'displayBlocks', url: '/prodHome/v1/displayBlocks', dis: '首页展示模块查询' },
  { code: '', key: 'configureBlocksUpdate', url: '/prodHome/v1/configureBlocksUpdate', dis: '首页可配置模块更新' },
  { code: '', key: 'configureBlocks', url: '/prodHome/v1/configureBlocks', dis: '首页可配置模块查询' },
  { code: '', key: 'prodIncomeTrendStat', url: '/prodHome/v1/prodIncomeTrendStat', dis: '产品收入趋势分析' },
  { code: '', key: 'prodSalesDistributeStat', url: '/prodHome/v1/prodSalesDistributeStat', dis: '产品销量分布统计' },
  { code: '', key: 'prodSalesTrendStat', url: '/prodHome/v1/prodSalesTrendStat', dis: '产品销量趋势分析' },
  { code: '', key: 'prodNoticePage', url: '/prodHome/v1/prodNoticePage', dis: '产品公告首页（查询所有）' },
];
