export default [
  { code: '', key: 'queryInvestPlanList', url: '/anxinInvestPlanList/v1/queryInvestPlanList', dis: '产品销售一体化-定投查询列表' },
  { code: '', key: 'queryAIPDeductionDetails', url: '/anxinProductList/v1/queryAIPDeductionDetails', dis: '产品销售一体化-定投查询-扣款明细' },
  { code: '', key: 'queryFinancailCusList', url: '/anxinFinancailCusList/v1/queryFinancailCusList', dis: '产品销售一体化-理财客户列表' },
  { code: '', key: 'queryStatisticsCycleConfig', url: '/anxinProductList/v1/queryStatisticsCycleConfig', dis: '产品销售一体化-理财客户列表-查询统计周期' },
  { code: '', key: 'queryInvestPlanListExport', url: '/anxinInvestPlanList/v1/queryInvestPlanListExport', dis: '产品销售一体化-定投查询-导出表格' },
  { code: '', key: 'salesBoard', url: '/anxinProductList/v1/salesBoard', dis: '产品销售一体化-金融产品列表-销售看板' },
  { code: '', key: 'productDisplayColumn', url: '/anxinProductList/v1/productDisplayColumn', dis: '产品列表查询可显示列' },
  { code: '', key: 'myLastSearchScheme', url: '/anxinProductList/v1/myLastSearchScheme', dis: '产品列表 查询用户最近一次查询方案' },
  { code: '', key: 'productCusList', url: '/anxinProductList/v1/productCusList', dis: '产品销售一体化-产品详情-客户列表' },
  { code: '', key: 'queryStatisticsCycleConfig', url: '/anxinProductList/v1/queryStatisticsCycleConfig', dis: '查询统计周期' },
  { code: '', key: 'queryProductList', url: '/anxinProductList/v1/queryProductList', dis: '安信金融产品--产品列表' },
  { code: '', key: 'productCommonSearch', url: '/anxinProductList/v1/productCommonSearch', dis: '产品列表-获取产品常用搜索' },
  { code: '', key: 'exportDataFinancailCusList', url: '/anxinFinancailCusList/v1/exportDataFinancailCusList', dis: '产品销售一体化-理财客户列表-列表导出' },
  { code: '', key: 'productListExport', url: '/anxinProductList/v1/productListExport', dis: '产品销售一体化-产品列表-列表导出' },
  { code: '', key: 'cusProductList', url: '/anxinProductList/v1/cusProductList', dis: '产品销售一体化-理财客户列表-客户持有产品列表' },
  { code: '', key: 'chooseMyProduct', url: '/anxinProductList/v1/chooseMyProduct', dis: '产品列表 自选产品' },
  { code: '', key: 'queryOtherListDisplayColumn', url: '/anxinProductList/v1/queryOtherListDisplayColumn', dis: '查询其他列表展示指标' },
  { code: '', key: 'queryUserPermission', url: '/anxinProductList/v1/queryUserPermission', dis: '查询其他列表展示指标' },
  { code: '', key: 'querySingleProductDetail', url: '/anxinProductList/v1/querySingleProductDetail', dis: '单产品查询' },
  { code: '', key: 'productCountAggs', url: '/anxinProductList/v1/productCountAggs', dis: '字典项对应的统计值' },
  { code: '', key: 'productCusListExport', url: '/anxinProductList/v1/productCusListExport', dis: '产品全景-客户列表-导出' },
  { code: '', key: 'cusProductListExport', url: '/anxinProductList/v1/cusProductListExport', dis: '理财客户-客户明细-导出' },
  { code: '', key: 'saleAndIncomeList', url: '/saleAndIncome/v1/querySaleAndIncomeList', dis: '销量与创收-表格查询' },
  { code: '', key: 'saleAndIncomeListExport', url: '/saleAndIncome/v1/exportDataSaleAndIncomeList', dis: '销量与创收-导出' },
  { code: '', key: 'queryStatisticalCycle', url: '/incomeAndReward/v1/queryStatisticalCycle', dis: '查询统计周期' },
  { code: '', key: 'confirmUploadComplete', url: '/incomeAndReward/v1/confirmUploadComplete', dis: '确认上传完成' },
  { code: '', key: 'queryUploadList', url: '/incomeAndReward/v1/queryUploadList', dis: '查询上传记录列表' },
  { code: '', key: 'inAndReAuditImport', url: '/anxinProductList/v1/inAndReAuditImport', dis: '收入与奖励附件上传确认' },
  { code: '', key: 'inAndReAuditDelete', url: '/anxinProductList/v1/inAndReAuditDelete', dis: '收入与奖励附件确认删除' },
  { code: '', key: 'queryIncomeAndRewardList', url: '/incomeAndReward/v1/queryIncomeAndRewardList', dis: '收入与奖励列表' },
  { code: '', key: 'exportDataIncomeAndRewardList', url: '/incomeAndReward/v1/exportDataIncomeAndRewardList', dis: '收入与奖励列表导出' },

  { code: '', key: 'queryBackLogList', url: '/app/v1/queryBackLogList', dis: '工作-待办列表信息查询' },
  { code: '', key: 'queryServieBackLogList', url: '/app/v1/queryServiceBackLogList', dis: '工作-事件列表信息查询' },
  { code: '', key: 'queryCalContent', url: '/app/v1/queryCalContent', dis: '工作-日历内容查询' },
  { code: '', key: 'queryUserTaskCust', url: '/app/v1/queryUserTaskCust', dis: '工作-服务客户列表查询' },
  { code: '', key: 'quertTaskServiceLog', url: '/app/v1/quertTaskServiceLog', dis: '工作-查看已服务跟进日志' },
  { code: '', key: 'saveOverLookUserTaskCust', url: '/app/v1/saveOverLookUserTaskCust', dis: '工作-任务详情忽略任务编辑保存' },
  { code: '', key: 'queryEventDetailCusList', url: '/app/v1/queryEventDetailCusList', dis: 'MOT事件详情客户列表' },
  { code: '', key: 'queryEventDetail', url: '/app/v1/queryEventDetail', dis: 'MOT事件详情' },
  { code: '', key: 'queryRelationEventList', url: '/app/v1/queryRelationEventList', dis: 'MOT事件关联事件列表' },
  { code: '', key: 'queryWorkSetting', url: '/app/v1/queryWorkSetting', dis: '工作设置列表' },
  { code: '', key: 'saveWorkSetting', url: '/app/v1/saveWorkSetting', dis: '工作设置保存操作' },
  { code: '', key: 'queryUserTaskListInformation', url: '/app/v1/queryUserTaskListInformation', dis: '任务-我的任务列表信息查询' },
  { code: '', key: 'queryUserTaskListInformationDetails', url: '/app/v1/queryUserTaskListInformationDetails', dis: '任务-我的任务列表信息详情查询' },
  { code: '', key: 'saveTakeNotesProcessInfo', url: '/app/v1/saveTakeNotesProcessInfo', dis: '待办-记录查看流程详情保存' },
  { code: '', key: 'ignoreEvent', url: '/app/v1/ignoreEvent', dis: '忽略事件操作' },
  { code: '', key: 'saveUserTaskStrikeOut', url: '/app/v1/saveUserTaskStrikeOut', dis: '我的任务列表任务删除' },
  { code: '', key: 'addTask', url: '/app/v1/AddTask', dis: '新c5-创建任务' },
  { code: '', key: 'queryBusinessDetails', url: '/app/v1/QueryBusinessDetails', dis: '新c5-创建任务-任务业务明细查询' },
  { code: '', key: 'appRetrofitV1Upload', url: '/AppRetrofit/v1/upload/sendMessage', dis: '新c5-创建任务-附件上传' },
  { code: '', key: 'queryCueTaskDetails', url: '/app/v1/QueryCueTaskDetails', dis: '新c5-创建任务-线索流素材和营销类型查询' },
  { code: '', key: 'queryMarketMaterials', url: '/app/v1/queryMarketMaterials', dis: '新c5-创建任务-查询展业素材列表' },
  { code: '', key: 'queryUserTaskCustNew', url: '/app/v1/queryUserTaskCustNew', dis: '新c5-代办线索流任务表格查询' },

  { code: '', key: 'queryCusInfo', url: '/app/v1/queryCusInfo', dis: '查询客户基本信息档案' },
  { code: '', key: 'queryCusLabel', url: '/app/v1/queryCusLabel', dis: '查询客户30S认知' },
  { code: '', key: 'queryAnaCalendar', url: '/diagnose/v1/queryAnaCalendar', dis: '查询账户分析日历' },
  { code: '', key: 'queryAnaDetail', url: '/diagnose/v1/queryAnaDetail', dis: '查询各项能力得分详情' },
  { code: '', key: 'queryAnaScore', url: '/diagnose/v1/queryAnaScore', dis: '查询各项能力得分' },
  { code: '', key: 'queryOpeCalendar', url: '/diagnose/v1/queryOpeCalendar', dis: '操作诊断日历' },
  { code: '', key: 'queryOpeSpecial', url: '/diagnose/v1/queryOpeSpecial', dis: '查询用户操作诊断报告' },
  { code: '', key: 'queryCusSuitInfo', url: '/app/v1/queryCusSuitInfo', dis: '查询客户适当性数据' },
  { code: '', key: 'queryStockKLine', url: '/card/v1/queryStockKLine', dis: '查询K线' },
  { code: '', key: 'queryStockTrendChart', url: '/card/v1/queryStockTrendChart', dis: '分时走势图' },

  { code: '', key: 'getChannelInfoModel', url: '/channel/v1/getChannelInfo', dis: '获取渠道信息' },
  { code: '', key: 'channelManagementModel', url: '/channel/v1/channelManagement', dis: '管理渠道，包括新增、修改、启用、禁用' },
  { code: '', key: 'optionalStaffList', url: '/staffrelationship/v1/optionalStaffList', dis: '获取可选人员列表' },
  { code: '', key: 'getOperateRecord', url: '/channel/v1/getOperateRecord', dis: '获取操作日志' },
  { code: '', key: 'getGroupInfoModel', url: '/channel/v1/getGroupInfo', dis: '获取小组信息' },
  { code: '', key: 'findHomePage', url: '/diagnose/v1/findHomePage', dis: 'T-1账单首页接口文档' },
  { code: '', key: 'findstocks', url: '/diagnose/v1/findstocks', dis: '账单区间内股票列表接口文档' },
  { code: '', key: 'findfinancials', url: '/diagnose/v1/findfinancials', dis: '账单区间基金理财列表接口文档' },
  { code: '', key: 'nationaldebtdetail', url: '/diagnose/v1/nationaldebtdetail', dis: '区间内国债逆回购接口' },
  { code: '', key: 'findOtherDetails', url: '/diagnose/v1/findOtherDetails', dis: 'T-1账单其他收益明细' },
  { code: '', key: 'findDetailed', url: '/diagnose/v1/findDetailed', dis: 'T-1账单收益明细查询接口文档' },
  { code: '', key: 'findCalenderList', url: '/diagnose/v1/findCalenderList', dis: 'T-1账单日历接口文档' },
  { code: '', key: 'groupManagement', url: '/channel/v1/groupManagement', dis: '管理渠道小组' },
  { code: '', key: 'getAchievementAnalysis', url: '/channel/v1/getAchievementAnalysis', dis: '获取业绩分析' },
  { code: '', key: 'getChannelCustList', url: '/channel/v1/getChannelCustList', dis: '获取渠道客户列表' },
  { code: '', key: 'getAchievementAnalysisExport', url: '/channel/v1/getAchievementAnalysisExport', dis: '查询渠道/小组业绩分析导出' },
  { code: '', key: 'getChannelCustListExport', url: '/channel/v1/getChannelCustListExport', dis: '渠道客户导出' },
  { code: '', key: 'getChannelInfoExport', url: '/channel/v1/getChannelInfoExport', dis: '渠道信息报表导出' },
  { code: '', key: 'getMyQRCode', url: '/channel/v1/getMyQRCode', dis: '获取我的二维码' },
  { code: '', key: 'saveOperateRecord', url: '/channel/v1/saveOperateRecord', dis: '保存操作日志' },
  { code: '', key: 'queryStaffTips', url: '/staffrelationship/v1/queryStaffTips', dis: '获取管理员(模糊搜索)' },
  { code: '', key: 'getCommissionAgreementInfo', url: '/channel/v1/getCommissionAgreementInfo', dis: '佣金协议' },
  { code: '', key: 'queryStaffPracticeInfo', url: '/channel/v1/queryStaffPracticeInfo', dis: '获取营业部有执业资格人员信息' },
  // { code: '', key: 'getMyQRCode', url: '/ftq/postersShare/v1/getMyQrCode', dis: '获取我的二维码' },
  { code: '', key: 'getMyQrCodeWithLogo', url: '/ftq/postersShare/v1/emp/getMyQrCodeWithLogo', dis: '获取我的二维码带logo' },
  { code: '', key: 'queryChannelAuthorityDepartment', url: '/channel/v1/queryChannelAuthorityDepartment', dis: '获取渠道管理营业部信息' },
  { code: '', key: 'optionFindHomePage', url: '/app/v1/findHomePage', dis: '期权T-1账单首页接口' },
  { code: '', key: 'optionFindHomePageList', url: '/app/v1/findHomePageList', dis: '期权T-1账单列表' },
  { code: '', key: 'optionFindCalenderList', url: '/app/v1/findCalenderList', dis: '期权账户T-1账单日历接口文档' },
  { code: '', key: 'optionFindDetailed', url: '/app/v1/findDetailed', dis: '期权账户T-1账单收益明细查询接口文档' },
  { code: '', key: 'queryUserRoleInfo', url: '/channel/v1/queryUserRoleInfo', dis: '期权账户T-1账单收益明细查询接口文档' },
  { code: '', key: 'updateday', url: '/diagnose/v1/updateday', dis: 'T-1账单更新最新日期查询' },

  // 历史持仓
  { code: '', key: 'hisstocksdetail', url: '/diagnose/v1/hisstocksdetail', dis: '获取历史持股详情' },
  { code: '', key: 'hisstockslist', url: '/diagnose/v1/hisstockslist', dis: '获取历史持股列表' },
  { code: '', key: 'hisfundsdetail', url: '/diagnose/v1/hisfundsdetail', dis: '获取历史基金详情' },
  { code: '', key: 'hisfundslist', url: '/diagnose/v1/hisfundslist', dis: '获取历史基金列表' },
  { code: '', key: 'jyhgupdateday', url: '/diagnose/v1/jyhgupdateday', dis: '获取最新日期' },
  { code: '', key: 'findHqDeal4hisStock', url: '/diagnose/v1/findHqDeal4hisStock', dis: '查询股票收盘价走势' },
  // 最新持仓
  { code: '', key: 'findPostion', url: '/app/v1/findPostion', dis: '最新持仓列表' },
  { code: '', key: 'findPostionNameAndCode', url: '/app/v1/findPostionNameAndCode', dis: '最新持仓-持仓名称查询' },
  { code: '', key: 'findPositionSummary', url: '/app/v1/findPositionSummary', dis: '最新持仓概要' },
  { code: '', key: 'findAvailableAccount', url: '/app/v1/findAvailableAccount', dis: '查询可用账户' },
  { code: '', key: 'findPostionExport', url: '/app/v1/findPostionExport', dis: '导出' },

  //基金投顾
  { code: '', key: 'queryPcxJjtgYjbb', url: '/app/v1/queryPcxJjtgYjbb', dis: '基金投顾业绩报表' },
  { code: '', key: 'queryZhdm', url: '/app/v1/queryZhdm', dis: '基金投顾策略代码' },

  //渠道二期
  { code: '', key: 'getachievements', url: '/channel/v1/getachievements', dis: '查询每月业绩' },
  { code: '', key: 'getChannelRecords', url: '/channel/v1/getChannelRecords', dis: '渠道小组趋势数据分析' },
  { code: '', key: 'getSalarys', url: '/channel/v1/getSalarys', dis: '薪酬统计' },
  { code: '', key: 'getAllAccountDate', url: '/channel/v1/getAllAccountDate', dis: '全部开户数据分析' },
  { code: '', key: 'getTracksCustInfoList', url: '/channel/v1/getTracksCustInfoList', dis: '开户跟踪客户列表' },
  { code: '', key: 'getChnnlAccnBreakCust', url: '/channel/v1/getChnnlAccnBreakCust', dis: '查询渠道开户中断客户信息' },
  { code: '', key: 'getChannelRecordsExport', url: '/channel/v1/getChannelRecordsExport', dis: '小组趋势导出' },
  { code: '', key: 'getachievementsExport', url: '/channel/v1/getachievementsExport', dis: '小组绩效导出' },
  { code: '', key: 'getSalarysExport', url: '/channel/v1/getSalarysExport', dis: '薪资统计导出' },
  { code: '', key: 'getAllAccountDateExport', url: '/channel/v1/getAllAccountDateExport', dis: '全部开户数据导出' },
  { code: '', key: 'saveChnnlAccnBreakCust', url: '/channel/v1/saveChnnlAccnBreakCust', dis: '中断客户追踪操作' },
  { code: '', key: 'channelServiceRecord', url: '/channel/v1/channelServiceRecord', dis: '填写服务记录' },
  { code: '', key: 'getAllAccountDatePop', url: '/channel/v1/getAllAccountDatePop', dis: '获取全部开户数据弹窗' },
  { code: '', key: 'getAllAccountDatePopExport', url: '/channel/v1/getAllAccountDatePopExport', dis: '获取全部开户数据弹窗导出' },

  //客户等级权益
  { code: '', key: 'queryLevelBenefit', url: '/panoramic/v1/queryLevelBenefit', dis: '查询等级与权益详细数据' },
  { code: '', key: 'queryBenefitUserList', url: '/panoramic/v1/queryBenefitUserList', dis: '查询对应等级客户列表' },
  { code: '', key: 'queryLockBenefit', url: '/panoramic/v1/queryLockBenefit', dis: '查询当前等级未解锁权益' },
  { code: '', key: 'queryCustMessage', url: '/panoramic/v1/queryCustMessage', dis: '查询客户等级与权益页面客户号和客户名称' },
  { code: '', key: 'queryBenefitName', url: '/panoramic/v1/queryBenefitName', dis: '查询对应等级的权益名称' },
  { code: '', key: 'queryCustBenefit', url: '/panoramic/v1/queryCustBenefit', dis: '查询用户权益列表' },

  //员工首页
  { code: '', key: 'queryCustBasicInfo', url: '/page/v1/queryCustBasicInfo', dis: '查询员工基本信息' },
  { code: '', key: 'queryNewCustchanges', url: '/page/v1/queryNewCustchanges', dis: '查询新增客户变化' },
  { code: '', key: 'queryCustGradeDis', url: '/page/v1/queryCustGradeDis', dis: '客户等级分布饼图' },
  { code: '', key: 'queryCustServiceDis', url: '/page/v1/queryCustServiceDis', dis: '客户业务分布饼图' },
  { code: '', key: 'queryCustAssetOverview', url: '/page/v1/queryCustAssetOverview', dis: '查询资产概况' },
  { code: '', key: 'queryProportionOfAsset', url: '/page/v1/queryProportionOfAsset', dis: '资产分类占比' },
  { code: '', key: 'queryZcRankInfo', url: '/page/v1/queryZcRankInfo', dis: '资产排名情况' },
  { code: '', key: 'queryAssetTrendAnalysis', url: '/page/v1/queryAssetTrendAnalysis', dis: '资产趋势分析' },
  { code: '', key: 'queryIncomeGeneInfo', url: '/page/v1/queryIncomeGeneInfo', dis: '业绩创收' },
  { code: '', key: 'queryWorksInfo', url: '/page/v1/queryWorksInfo', dis: '工作模块' },
  { code: '', key: 'queryServiceChange', url: '/page/v1/queryServiceChange', dis: '业务机会字典' },
  { code: '', key: 'invstmentAdviserSaver', url: '/anxinProductList/v1/invstmentAdviserSaver', dis: '分享信息同步c端' },
  { code: '', key: 'QueryPcxJjtgYjbbExport', url: '/app/v1/QueryPcxJjtgYjbbExport', dis: '基金投顾业绩导出' },
  { code: '', key: 'queryEventInfoCus', url: '/app/v1/queryEventInfo', dis: '系统平台--事件管理--事件表头--客户' },
  { code: '', key: 'queryEventCustomerList', url: '/app/v1/queryEventCustomerList', dis: '系统平台--事件管理--事件表头--客户' },
  { code: '', key: 'queryStrategyDetail', url: '/app/v1/queryStrategyDetail', dis: '策略配置明细' },

  //排行榜
  { code: '', key: 'queryIndex', url: '/staffpormance/v1/queryIndex', dis: '查询人员可选指标' },
  { code: '', key: 'queryDepartIndexValue', url: '/staffpormance/v1/queryDepartIndexValue', dis: '查询辖属营业部排行列表' },
  { code: '', key: 'queryStaffIndexValue', url: '/staffpormance/v1/queryStaffIndexValue', dis: '查询员工排行列表' },
  { code: '', key: 'queryEmpInfo', url: '/assessment/v1/queryEmpInfo', dis: '查询员工列表' },

  //员工主页绩效查询
  { code: '', key: 'queryStaffEfficiency', url: '/staffpormance/v1/queryStaffEfficiency', dis: '员工主页绩效查询' },
  { code: '', key: 'queryAssIndicators', url: '/staffpormance/v1/queryAssIndicators', dis: '员工主页绩效查询2' },
  { code: '', key: 'queryAssessmentScore', url: '/staffpormance/v1/queryAssessmentScore', dis: '查询考核得分计算公式' },
  { code: '', key: 'queryIndexCustDetails', url: '/staffpormance/v1/queryIndexCustDetails', dis: '查询员工指标明细客户' },
  { code: '', key: 'queryScoreDetails', url: '/staffpormance/v1/queryScoreDetails', dis: '查询员工得分详情' },
  { code: '', key: 'queryCustIndi', url: '/assessment/v1/queryCustIndi', dis: '考核指标查询' },
  { code: '', key: 'operateCustIndi', url: '/assessment/v1/operateCustIndi', dis: '考核指标查询' },
  { code: '', key: 'queryCalcFormulaParam', url: '/assessment/v1/queryCalcFormulaParam', dis: '计算公式参数查询' },
  { code: '', key: 'queryViewColumns', url: '/staffpormance/v1/queryViewColumns', dis: '查询展示列' },

  //客户指标接口
  { code: '', key: 'addCustIndex', url: '/staffpormance/v1/AddCustIndex', dis: '新增客户指标' },
  { code: '', key: 'deleteCustCode', url: '/staffpormance/v1/deleteCustCode', dis: '删除客户指标' },
  { code: '', key: 'updateCustIndexDetails', url: '/staffpormance/v1/updateCustIndexDetails', dis: '编辑客户指标' },
  { code: '', key: 'queryCustCodeObscure', url: '/staffpormance/v1/queryCustCodeObscure', dis: '客户指标模糊查询' },
  { code: '', key: 'queryCustMetricsTree', url: '/staffpormance/v1/queryCustMetricsTree', dis: '查询客户指标树' },
  { code: '', key: 'queryCustIndiDetails', url: '/staffpormance/v1/queryCustIndiDetails', dis: '查询客户指标详情' },
  { code: '', key: 'getUpdateStatus', url: '/staffpormance/v1/getUpdateStatus', dis: '客户指标校验' },
  { code: '', key: 'updateIndexUpAndDown', url: '/staffpormance/v1/updateIndexUpAndDown', dis: '指标上下架' },

  //产品机会
  { code: '', key: 'getAIGridStockPool', url: '/AppRetrofit/v1/getAIGridStockPool', dis: '股票池' },
  { code: '', key: 'queryCustomerStockPool', url: '/AppRetrofit/v1/queryCustomerStockPool', dis: '客户持仓查询' },

  //潜客处理
  { code: '', key: 'saveCompleteUserTaskCust', url: '/app/v1/saveCompleteUserTaskCust', dis: '潜客处理' },
];
