export default [
  { code: '', key: 'operateTaskList', url: '/operateManage/v1/operateTaskList', dis: '运营任务列表查询' },
  { code: '', key: 'importantLevelStatistic', url: '/operateManage/v1/importantLevelStatistic', dis: '运营任务统计分析(按重要程度统计)' },
  { code: '', key: 'eventTypeStatistic', url: '/operateManage/v1/eventTypeStatistic', dis: '运营任务统计分析(按事件类型统计)' },
  { code: '', key: 'operateTaskUrge', url: '/operateManage/v1/operateTaskUrge', dis: '运营任务催办' },
  { code: '', key: 'operateTaskExec', url: '/operateManage/v1/operateTaskExec', dis: '运营任务执行' },
  { code: '', key: 'operateTaskCancel', url: '/operateManage/v1/operateTaskCancel', dis: '运营任务取消' },
  { code: '', key: 'operateTaskAdjust', url: '/operateManage/v1/operateTaskAdjust', dis: '运营任务调整' },
  { code: '', key: 'prodOperateCalendar', url: '/operateManage/v1/prodOperateCalendar', dis: '产品运营日历查询' },
  { code: '', key: 'querySaleSupportRoadshow', url: '/roadShow/v1/querySaleSupportRoadshow', dis: '员工销售支持-路演展示' },
  { code: '', key: 'querySaleSupportRoadshowFiles', url: '/roadShow/v1/querySaleSupportRoadshowFiles', dis: '员工销售支持-路演纪要' },
  { code: '', key: 'querySaleSupportRoadshowSendMsg', url: '/roadShow/v1/querySaleSupportRoadshowSendMsg', dis: '员工销售支持-发送消息' },
  { code: '', key: 'queryProcessNavigation', url: '/navigation/v1/queryProcessNavigation', dis: '流程导航查询' },
  { code: '', key: 'queryOrgClass', url: '/orgHome/v1/queryOrgClass', dis: '机构分类查询' },
  { code: '', key: 'queryOrgComposite', url: '/orgHome/v1/queryOrgComposite', dis: '机构综合查询' },
  { code: '', key: 'queryProductInfoFuzzy', url: '/navigation/v1/queryProductInfoFuzzy', dis: '产品信息模糊查询（仅指有审批记录的产品）' },
  { code: '', key: 'queryProductProcessStep', url: '/navigation/v1/queryProductProcessStep', dis: '产品流程步骤查询' },
  { code: '', key: 'queryProductProgressTracking', url: '/navigation/v1/queryProductProgressTracking', dis: '产品进度跟踪查询' },
  { code: '', key: 'orgCompositeExport', url: '/orgHome/v1/orgCompositeExport', dis: '合作机构库导出' },
  { code: '', key: 'orgCompositeExport', url: '/orgHome/v1/orgCompositeExport', dis: '合作机构库导出' },
  { code: '', key: 'queryAbnormalEventsNum', url: '/dataMonitor/qualityCheck/queryAbnormalEventsNum', dis: '异常事件数量查询' },
  { code: '', key: 'queryAbnormalIndex', url: '/dataMonitor/qualityCheck/queryAbnormalIndex', dis: '查询异常事件指标分布' },
  { code: '', key: 'queryCheckEvent', url: '/dataMonitor/qualityCheck/queryCheckEvent', dis: '数据质检事件大屏查询' },
  { code: '', key: 'flowBasicInfoQuery', url: '/operateManage/flowMonitor/flowBasicInfoQuery', dis: '流程基本信息查询' },
  { code: '', key: 'flowListQuery', url: '/operateManage/flowMonitor/flowListQuery', dis: '流程列表信息查询' },
  { code: '', key: 'flowNodeInfoQuery', url: '/operateManage/flowMonitor/flowNodeInfoQuery', dis: '流程节点信息查询' },
];
