export default [
  { code: '', key: 'queryOwnershipDetail', url: '/v1/queryOwnershipDetail', dis: '收入与奖励--保有明细' },
  { code: '', key: 'queryProductAppointment', url: '/diagnose/v1/queryProductAppointment', dis: '产品预约查询' },
  { code: '', key: 'productAppointmentExport', url: '/diagnose/v1/productAppointmentExport', dis: '产品预约查询--导出' },
  { code: '', key: 'exportOwnershipDetail', url: '/v1/exportOwnershipDetail', dis: '保有明细--导出' },
  { code: '', key: 'queryProductType', url: '/v1/queryProductType', dis: '保有明细--大类 子类' },

  //业务机会优化
  { code: '', key: 'queryInvalidCustomer', url: '/AppRetrofit/v1/queryInvalidCustomer', dis: '客户-查询无效户标签客户' },
  { code: '', key: 'queryTianlibao', url: '/AppRetrofit/v1/queryTianlibao', dis: '客户-查询天利宝相关客户' },
  { code: '', key: 'marginFinance', url: '/AppRetrofit/v1/marginFinance', dis: '客户-查询融资融券相关客户' },
  { code: '', key: 'stockOptions', url: '/AppRetrofit/v1/stockOptions', dis: '客户-查询股票期权相关客户' },
  { code: '', key: 'HongkongStock', url: '/AppRetrofit/v1/HongkongStock', dis: '客户-查询港股通相关客户' },
  { code: '', key: 'queryThreeBoard', url: '/AppRetrofit/v1/queryThreeBoard', dis: '客户-查询新三板相关客户' },
  { code: '', key: 'querySTARMarket', url: '/AppRetrofit/v1/querySTARMarket', dis: '客户-查询科创板相关客户' },
  { code: '', key: 'queryGEMarket', url: '/AppRetrofit/v1/queryGEMarket', dis: '客户-查询创业板相关客户' },
  { code: '', key: 'queryBSE', url: '/AppRetrofit/v1/queryBSE', dis: '客户-查询北交所相关客户' },
  { code: '', key: 'queryFundInvestmentAdvisor', url: '/AppRetrofit/v1/queryFundInvestmentAdvisor', dis: '客户-查询基金投顾相关客户' },
  { code: '', key: 'queryTag', url: '/AppRetrofit/v1/queryTag', dis: '客户-查询标签列表' },
  { code: '', key: 'queryCustomerGroup', url: '/AppRetrofit/v1/queryCustomerGroupList', dis: '客户-查询客户群列表' },
  { code: '', key: 'queryScenes', url: '/AppRetrofit/v1/queryScenes', dis: '客户-查询场景列表' },
  { code: '', key: 'queryMarketMaterial', url: '/app/v1/queryMarketMaterials', dis: '客户-查询展业素材' },
  { code: '', key: 'queryInvalidCustomerExport', url: '/AppRetrofit/v1/queryInvalidCustomerExport', dis: '客户-无效户标签客户导出' },
  { code: '', key: 'queryTianlibaoExport', url: '/AppRetrofit/v1/queryTianlibaoExport', dis: '客户-天利宝客户导出' },
  { code: '', key: 'marginFinanceExport', url: '/AppRetrofit/v1/marginFinanceExport', dis: '客户-融资融券导出' },
  { code: '', key: 'stockOptionsExport', url: '/AppRetrofit/v1/stockOptionsExport', dis: '客户-股票期权导出' },
  { code: '', key: 'HongkongStockExport', url: '/AppRetrofit/v1/HongkongStockExport', dis: '客户-港股通导出' },
  { code: '', key: 'queryThreeBoardExport', url: '/AppRetrofit/v1/queryThreeBoardExport', dis: '客户-新三板导出' },
  { code: '', key: 'querySTARMarketExport', url: '/AppRetrofit/v1/querySTARMarketExport', dis: '客户-科创板导出' },
  { code: '', key: 'queryGEMarketExport', url: '/AppRetrofit/v1/queryGEMarketExport', dis: '客户-创业板导出' },
  { code: '', key: 'queryBSEExport', url: '/AppRetrofit/v1/queryBSEExport', dis: '客户-北交所导出' },
  { code: '', key: 'queryFundInvestmentAdvisorExport', url: '/AppRetrofit/v1/queryFundInvestmentAdvisorExport', dis: '客户-基金投顾导出' },

  { code: '', key: 'queryQualificationInfo', url: '/page/v1/queryQualificationInfo', dis: '员工主页新增' },

  //工作统计
  { code: '', key: 'getEventFinishStatResponse', url: '/AppRetrofit/v1/getEventFinishStatResponse', dis: '事件完成情况' },
  { code: '', key: 'getWorkStatResponse', url: '/AppRetrofit/v1/getWorkStatResponse', dis: '工作统计' },
  { code: '', key: 'getEventListResponse', url: '/AppRetrofit/v1/getEventListResponse', dis: '员工维度事件列表查询' },
  { code: '', key: 'getDepartmentStatDetailResponse', url: '/AppRetrofit/v1/getDepartmentStatDetailResponse', dis: '按分支机构统计' },
  { code: '', key: 'getWorkStatDetailResponse', url: '/AppRetrofit/v1/getWorkStatDetailResponse', dis: '按工作类型统计' },
  { code: '', key: 'getStaffStatDetailResponse', url: '/AppRetrofit/v1/getStaffStatDetailResponse', dis: '按员工统计' },
  { code: '', key: 'getStaffDetailResponse', url: '/AppRetrofit/v1/getStaffDetailResponse', dis: '员工明细' },
  { code: '', key: 'getEventPushStatResponse', url: '/AppRetrofit/v1/getEventPushStatResponse', dis: '事件推送' },
  { code: '', key: 'getMotTypeResponse', url: '/AppRetrofit/v1/getMotTypeResponse', dis: '获取所有mot类型' },
  { code: '', key: 'getServiceDetailResponse', url: '/AppRetrofit/v1/getServiceDetailResponse', dis: '查询服务详情' },
  { code: '', key: 'getHeadOfficeResponse', url: '/AppRetrofit/v1/getHeadOfficeResponse', dis: '查询是否总部人员' },

  { code: '', key: 'getEventListResponseExport', url: '/AppRetrofit/v1/getEventListResponseExport', dis: '员工维度事件列表导出' },
  { code: '', key: 'getStaffDetailResponseExport', url: '/AppRetrofit/v1/getStaffDetailResponseExport', dis: '员工明细导出' },
  { code: '', key: 'getStaffStatDetailResponseExport', url: '/AppRetrofit/v1/getStaffStatDetailResponseExport', dis: '员工统计导出' },
  { code: '', key: 'getWorkStatDetailResponseExport', url: '/AppRetrofit/v1/getWorkStatDetailResponseExport', dis: '工作统计导出' },
  { code: '', key: 'getDepartmentStatDetailResponseExport', url: '/AppRetrofit/v1/getDepartmentStatDetailResponseExport', dis: '按分支机构导出' },

  //排行榜
  { code: '', key: 'queryDepartIndexValueExport', url: '/staffpormance/v1/queryDepartIndexValueExport', dis: '部门排行榜导出' },
  { code: '', key: 'queryStaffIndexValueExport', url: '/staffpormance/v1/queryStaffIndexValueExport', dis: '员工个人排行榜导出' },

  { code: '', key: 'queryIndexCustDetailsExport', url: '/staffpormance/v1/queryIndexCustDetailsExport', dis: '员工绩效报表明细导出' },
  { code: '', key: 'queryRolePowerList', url: '/staffCommon/v1/queryRolePowerList', dis: '权限列表接口' },
  { code: '', key: 'queryCreditInfo', url: '/channel/v1/queryCreditInfo', dis: '获取企业信息' },
  { code: '', key: 'getAIGridStockPoolExport', url: '/AppRetrofit/v1/getAIGridStockPoolExport', dis: '股票池导出' },

  { code: '', key: 'queryStrategyToolInfo', url: '/allMentionCommission/interestOptional/v1/queryStrategyToolInfo', dis: '获取策略工具池列表' },
  { code: '', key: 'queryStrategyToolPositionInfo', url: '/allMentionCommission/interestOptional/v1/queryStrategyToolPositionInfo', dis: '客户持仓列表列表' },
  { code: '', key: 'queryStrategyToolStockInfo', url: '/allMentionCommission/interestOptional/v1/queryStrategyToolStockInfo', dis: '获取信号池股票列表' },
  { code: '', key: 'queryStrategyToolInfoExport', url: '/allMentionCommission/interestOptional/v1/queryStrategyToolInfoExport', dis: '策略工具池列表--导出' },
  { code: '', key: 'queryStrategyToolPositionInfoExport', url: '/allMentionCommission/interestOptional/v1/queryStrategyToolPositionInfoExport', dis: '客户持仓列表--导出' },
  { code: '',key: 'custProductDetail', url: '/anxinProductList/v1/custProductDetail', dis: '客户持仓列表数据' },
  { code: '',key: 'custProductDetailExport', url: '/anxinProductList/v1/custProductDetailExport', dis: '当前持仓导出' },
  { code: '', key: 'getBankGroupInfo', url: '/channel/v1/getBankGroupInfo', dis: '开户二维码名称--获取专属银行名称' },
];
